### ISSUE TITLE
[Widget] UI issues with scroll

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cow-fi#166]
Open https://cow.fi/widget --> there is a black horizontal scrollbar 
![image](https://github.com/cowprotocol/cow-fi/assets/70885163/ccb7553f-04ec-4047-86ac-c5bc5710a80e)

Press on the Connect Wallet button --> there is an ugly scrollbar in Win 11 
![image](https://github.com/cowprotocol/cow-fi/assets/70885163/f794eb7f-8653-42b9-9301-2037cea7f62d)

Approve/place order: grey area with a scroll  is displayed under an order placed/approval modal
![image](https://github.com/cowprotocol/cow-fi/assets/70885163/f1a528f4-70be-4e45-ba65-8de2aba2368e)

**Expected**: 
1. Remove black scrollbar
2. Enhance the scrollbar in the connect modal

**Comment by anxolin** [comment]
@fairlighteth is this still happening?

**Comment by shoom3301** [comment]
The 1st case is not relevant anymore
