### ISSUE TITLE
[CoW.fi] Show email on click of `Talk to us`

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cow-fi#179]
> To be honest, I don't like when webs use the mailto links. I don't use the native app for mail, I use a webmail

> I always prefer they show me the email. What about showing the email when you click on the button? 

> Feel free to ignore, as its not super important. But we could show/hide the email when you click. And we add a copy to clipboard button https://github.com/cowprotocol/cow-fi/blob/b017bec8015a23def710894de9c3931fee300ea9/components/CopyToClipboard/index.tsx#L4

_Originally posted by @anxolin in https://github.com/cowprotocol/cow-fi/pull/178#pullrequestreview-1979632155_

**Comment by anxolin** [comment]
Not too relevant. Closing for now
