### ISSUE TITLE
Enhancements to the Swag page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cow-fi#184]
I'd like to propose some enhancements to the SWAP page that can be fixed from our side (and reported in https://github.com/cowprotocol/cow-fi/pull/175#issuecomment-2031994025): 

- [ ] 1. Add a link to the ENS name

![image](https://github.com/cowprotocol/cow-fi/assets/70885163/cb7e76a7-5d0d-4169-908e-cdb0e179b866)

- [ ] 2. Add a link to terms and conditions on the last slide 

![link](https://github.com/cowprotocol/cow-fi/assets/70885163/637c4e72-6f85-4ef7-860c-2ef437d826b5)

- [x] 3.  ~~Add an additional field for user comments (just in case a user orders 4 jackets with 3 different sizes, so in the 'additional comments (if any)' field might be useful in this case.~~

**Comment by blacktieaccountant** [comment]
1. Added the ethscan URL
2. Aded
3. There is already a open field depending on units selected, to leave the size per SKU.

Thanks!

**Comment by alfetopito** [comment]
This has been addressed, no?

**Comment by elena-zh** [comment]
Indeed... Closing the issue, thank you!
