### ISSUE TITLE
Issues related to rebranding

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cow-fi#21]
1. ~~Highlighted sections' headers are not readable~~
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7a337f5b-d6a2-4a94-b1c5-195089dcc322)

2. ~~It would be nice to remove link from brackets~~
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/66d5568d-dc5a-4fae-819e-36a9dd518b97)

3. It would be nice to add a hover effect to the Trade button 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/25e0effe-98b2-44a5-bfe6-a4aec20738cc)

4. ~~Should these icons be in line with top elements?~~
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/271a58a1-1c12-41d3-b7a0-85da9a66eb4a)

5. Mobile device: press on menu option and open it once again: options are dimmed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/279b8223-18dc-4c63-a6c1-32acbf52e4f9)
6. Open Careers page in a mobile device, then open menu and press son Developers: user is navigated not exactly to the section
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d5653e71-5f77-47fb-8391-62c3b0fb0ac2)
7. ~~Arrow for the link on the Careers page is shifted~~
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2824feaa-e5e3-435d-b43a-6aeda7053dbd)

**Comment by harisang** [comment]
Seems the Twitter hyperlink also points to the old mevprotection account.

![image](https://user-images.githubusercontent.com/64154020/185409854-60ac0c1f-1ab0-416c-9753-a9b03246508b.png)
