### ISSUE TITLE
Update Stats link

### ISSUE THREAD

**Issue by alongoni** [cowprotocol/cow-fi#34]
**Description**
![image](https://user-images.githubusercontent.com/622217/191618249-87dd7860-6a82-4ed8-b2f8-25b0c2a2149f.png)

The Analytics link (footer) should be replaced:

> from: https://dune.com/gnosis.protocol/Gnosis-Protocol-V2 
> to: https://dune.com/cowprotocol/Gnosis-Protocol-V2

**Comment by elena-zh** [comment]
Fixed!
