### ISSUE TITLE
Make 404 page look nicer

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cow-fi#42]
Currently, this text is displayed when a page is not found for Cow.fi
```
404 - Page Not Found

This page could not be found. Please go back to the home page.
```
where 'home page' link is almost invisible

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8f91b33c-8fb2-4abf-b319-673ab580c7ef)

It would be great to enhance this page (fix the link, add an image, add a better page header, etc.)

**Comment by fairlighteth** [comment]
Is this using the latest release branch? You should see this:

https://cow-web-git-release-051-cowswap.vercel.app/404

<img width="1535" alt="Screen Shot 2022-10-10 at 14 10 26" src="https://user-images.githubusercontent.com/31534717/194863415-8ee88e9e-831f-4bc1-8e6f-6663cfd480f8.png">

**Comment by elena-zh** [comment]
@fairlighteth , it was on Prod. 
In the latest branch the page looks great!
